import { ServicesHero } from "@/components/services/services-hero"
import { ComprehensiveServicesGrid } from "@/components/services/comprehensive-services-grid"
import { MembershipBenefits } from "@/components/services/membership-benefits"
import { SafetyGuidelines } from "@/components/services/safety-guidelines"
import { PricingSection } from "@/components/services/pricing-section"
import { Waves, Dumbbell, Heart, Users, Clock, Trophy, Shield, Droplets } from "lucide-react"

const services = [
  {
    icon: <Waves className="h-6 w-6" />,
    title: "Olympic Pool Training",
    description:
      "Professional training in our 50-meter Olympic-standard pool with lane reservations and coaching support.",
    features: [
      "50m Olympic-size pool with 8 lanes",
      "Temperature controlled at 78-80°F",
      "Advanced timing systems",
      "Underwater cameras for technique analysis",
      "Professional coaching available",
      "Competition preparation programs",
    ],
    rating: 4.9,
    reviews: 234,
    duration: "60-90 minutes",
    capacity: "8 swimmers per lane",
    ageGroup: "All Ages",
    difficulty: "Intermediate to Advanced",
    equipment: ["Lane ropes", "Pace clocks", "Kickboards", "Pull buoys", "Fins"],
    benefits: [
      "Improved cardiovascular fitness",
      "Enhanced swimming technique",
      "Competition readiness",
      "Professional coaching guidance",
      "Video analysis feedback",
    ],
    schedule: [
      "Monday-Friday: 6:00 AM - 8:00 AM",
      "Monday-Friday: 6:00 PM - 8:00 PM",
      "Saturday-Sunday: 8:00 AM - 12:00 PM",
    ],
    instructor: "Maria Rodriguez - Olympic Coach",
    image: "/placeholder.svg?height=300&width=400",
    popular: true,
  },
  {
    icon: <Users className="h-6 w-6" />,
    title: "Kids Swimming Lessons",
    description:
      "Fun and safe swimming lessons for children aged 3-12, focusing on water safety and fundamental swimming skills.",
    features: [
      "Small class sizes (max 6 kids)",
      "Certified pediatric instructors",
      "Progressive skill development",
      "Water safety education",
      "Fun games and activities",
      "Parent observation area",
    ],
    rating: 4.8,
    reviews: 456,
    duration: "45 minutes",
    capacity: "6 children max",
    ageGroup: "Ages 3-12",
    difficulty: "Beginner to Intermediate",
    equipment: ["Floatation devices", "Pool noodles", "Diving toys", "Kickboards"],
    benefits: [
      "Water safety skills",
      "Confidence building",
      "Physical fitness",
      "Social interaction",
      "Coordination development",
    ],
    schedule: ["Monday-Friday: 4:00 PM - 6:00 PM", "Saturday: 9:00 AM - 12:00 PM", "Sunday: 10:00 AM - 1:00 PM"],
    instructor: "Sarah Johnson - Pediatric Specialist",
    image: "/placeholder.svg?height=300&width=400",
    popular: true,
  },
  {
    icon: <Dumbbell className="h-6 w-6" />,
    title: "Aqua Fitness Classes",
    description:
      "Low-impact, high-intensity water workouts perfect for all fitness levels, combining cardio and strength training.",
    features: [
      "Low-impact joint-friendly exercise",
      "Full-body workout routines",
      "Resistance training in water",
      "Cardio and strength combination",
      "Music-driven classes",
      "Equipment provided",
    ],
    rating: 4.7,
    reviews: 189,
    duration: "50 minutes",
    capacity: "15 participants",
    ageGroup: "Adults 18+",
    difficulty: "All Levels",
    equipment: ["Water weights", "Resistance bands", "Pool noodles", "Aqua dumbbells"],
    benefits: [
      "Improved cardiovascular health",
      "Increased muscle strength",
      "Enhanced flexibility",
      "Reduced joint stress",
      "Calorie burning",
    ],
    schedule: ["Monday/Wednesday/Friday: 9:00 AM", "Tuesday/Thursday: 7:00 PM", "Saturday: 10:00 AM"],
    instructor: "Mike Thompson - Fitness Specialist",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    icon: <Heart className="h-6 w-6" />,
    title: "Aquatic Therapy",
    description:
      "Therapeutic water exercises for rehabilitation, injury recovery, and chronic pain management with certified therapists.",
    features: [
      "Heated therapy pool (92-94°F)",
      "Licensed physical therapists",
      "Individualized treatment plans",
      "Pain management techniques",
      "Mobility improvement focus",
      "Insurance accepted",
    ],
    rating: 4.9,
    reviews: 98,
    duration: "45 minutes",
    capacity: "1-on-1 or small groups",
    ageGroup: "All Ages",
    difficulty: "Therapeutic",
    equipment: ["Therapy equipment", "Flotation aids", "Resistance tools", "Mobility aids"],
    benefits: [
      "Pain reduction",
      "Improved mobility",
      "Faster recovery",
      "Reduced inflammation",
      "Enhanced quality of life",
    ],
    schedule: ["Monday-Friday: 8:00 AM - 5:00 PM", "By appointment only", "Emergency sessions available"],
    instructor: "Dr. Lisa Chen - Licensed PT",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    icon: <Trophy className="h-6 w-6" />,
    title: "Competitive Swim Team",
    description: "Elite training program for competitive swimmers preparing for regional and national competitions.",
    features: [
      "Elite coaching staff",
      "Competition preparation",
      "Video analysis technology",
      "Strength and conditioning",
      "Mental performance coaching",
      "Travel team opportunities",
    ],
    rating: 4.9,
    reviews: 67,
    duration: "2 hours",
    capacity: "Team-based",
    ageGroup: "Ages 8-18",
    difficulty: "Advanced",
    equipment: ["Professional timing", "Video analysis", "Strength equipment", "Competition gear"],
    benefits: [
      "Elite performance development",
      "Competition experience",
      "Scholarship opportunities",
      "Team building",
      "Leadership skills",
    ],
    schedule: ["Monday-Friday: 5:30 AM - 7:30 AM", "Monday-Friday: 4:00 PM - 6:00 PM", "Saturday: 7:00 AM - 10:00 AM"],
    instructor: "Coach Rodriguez - USA Swimming Certified",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    icon: <Clock className="h-6 w-6" />,
    title: "Adult Learn to Swim",
    description:
      "Patient, supportive instruction for adults who want to learn swimming or improve their technique in a comfortable environment.",
    features: [
      "Adult-only classes",
      "Patient instruction approach",
      "Overcoming water fear",
      "Technique development",
      "Flexible scheduling",
      "Private lessons available",
    ],
    rating: 4.8,
    reviews: 156,
    duration: "60 minutes",
    capacity: "4 adults max",
    ageGroup: "Adults 18+",
    difficulty: "Beginner to Intermediate",
    equipment: ["Flotation aids", "Kickboards", "Pool noodles", "Goggles"],
    benefits: [
      "Overcome water fear",
      "Learn life-saving skills",
      "Boost confidence",
      "Improve fitness",
      "Stress relief",
    ],
    schedule: ["Tuesday/Thursday: 7:00 PM - 8:00 PM", "Saturday: 2:00 PM - 4:00 PM", "Sunday: 3:00 PM - 5:00 PM"],
    instructor: "Jennifer Martinez - Adult Specialist",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    icon: <Shield className="h-6 w-6" />,
    title: "Water Safety & Lifeguard Training",
    description: "Comprehensive water safety courses and professional lifeguard certification programs.",
    features: [
      "Red Cross certification",
      "CPR and First Aid training",
      "Water rescue techniques",
      "Emergency response protocols",
      "Job placement assistance",
      "Recertification courses",
    ],
    rating: 4.9,
    reviews: 89,
    duration: "3 days intensive",
    capacity: "12 participants",
    ageGroup: "Ages 15+",
    difficulty: "Intermediate",
    equipment: ["Rescue equipment", "Training mannequins", "First aid supplies", "Certification materials"],
    benefits: [
      "Professional certification",
      "Life-saving skills",
      "Employment opportunities",
      "Community service",
      "Leadership development",
    ],
    schedule: ["Monthly weekend intensives", "Friday-Sunday: 9:00 AM - 5:00 PM", "Recertification: Monthly"],
    instructor: "Captain Tom Wilson - Red Cross Instructor",
    image: "/placeholder.svg?height=300&width=400",
    new: true,
  },
  {
    icon: <Droplets className="h-6 w-6" />,
    title: "Senior Water Aerobics",
    description:
      "Gentle, joint-friendly water exercises designed specifically for seniors to maintain fitness and mobility.",
    features: [
      "Senior-specific exercises",
      "Joint-friendly movements",
      "Social interaction focus",
      "Balance improvement",
      "Arthritis-friendly routines",
      "Warm water environment",
    ],
    rating: 4.8,
    reviews: 134,
    duration: "45 minutes",
    capacity: "20 participants",
    ageGroup: "Seniors 55+",
    difficulty: "Low Impact",
    equipment: ["Water weights", "Pool noodles", "Flotation belts", "Resistance bands"],
    benefits: ["Improved mobility", "Pain relief", "Social engagement", "Better balance", "Enhanced mood"],
    schedule: ["Monday/Wednesday/Friday: 10:00 AM", "Tuesday/Thursday: 2:00 PM", "Saturday: 11:00 AM"],
    instructor: "Nancy Davis - Senior Fitness Specialist",
    image: "/placeholder.svg?height=300&width=400",
  },
]

export default function ServicesPage() {
  return (
    <div className="min-h-screen">
      <ServicesHero />
      <ComprehensiveServicesGrid services={services} />
      <MembershipBenefits />
      <SafetyGuidelines />
    </div>
  )
}
